<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- ****************** ROBOT CONSTANTS *******************************  -->
  <!-- Definition of geometry parameters -->
  <!-- Gantry -->
  <xacro:property name="gantry_length" value="0.5" /> <!-- El gantry es una caja de LxLxL -->
  <xacro:property name="gantry_mass" value="1" />

  <!-- Base -->
  <xacro:property name="base_length" value="0.5" /> <!-- El eslabon BASE es un cilindro -->
  <xacro:property name="base_radius" value="0.5" />
  <xacro:property name="base_mass"   value="1" />

  <!-- Bicep -->
  <xacro:property name="bicep_length" value="5" /> <!-- El eslabon BICEP es una caja de WxHxL -->
  <xacro:property name="bicep_width" value="0.5" />
  <xacro:property name="bicep_height" value="0.5" />
  <xacro:property name="bicep_mass" value="1" />

  <!-- Forearm -->
  <xacro:property name="forearm_length" value="0.5" /> <!-- El eslabon FOREARM es una caja de WxHxL -->
  <xacro:property name="forearm_width" value="0.5" />
  <xacro:property name="forearm_height" value="0.5" />
  <xacro:property name="forearm_mass" value="1" />


  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}" />
      <mass value="${m}" />
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}"
        iyz="0.0" izz="${(m/12) * (w*w + h*h)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}" />
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0" iyy="${(m/12) * (3*r*r + h*h)}"
        iyz="0" izz="${(m/2) * (r*r)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}" />
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0"
        izz="${(2/5) * m * (r*r)}" />
    </inertial>
  </xacro:macro>

<!-- ****************** COORDINATES ORIGIN ***************************  -->
  <!-- Define the center of the robot -->
  <link name="world" />

  <!-- A simple fixed joint from our empty world link, to our base. -->
  <!-- The base origin is offset from the world origin. -->
  <joint name="gantry_joint" type="fixed">
    <origin xyz="${gantry_length/2} ${gantry_length/2} ${gantry_length/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="gantry_link" />
  </joint>



  <!-- ********************** GANTRY *********************************  -->
  <link name="gantry_link">
    <visual>
      <origin xyz="0 0 -${gantry_length/2}" rpy="0 0 0" />
      <geometry>
        <box size="${gantry_length} ${gantry_length} ${gantry_length}" />
      </geometry>
      <material name="Red">
        <color rgba="${255/255} ${0/255} ${0/255} 1.0" />
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 -${gantry_length/2}" rpy="0 0 0" />
      <geometry>
        <box size="${gantry_length} ${gantry_length} ${gantry_length}" />
      </geometry>
    </collision>

    <xacro:box_inertia m="${gantry_mass}" w="${gantry_length}" d="${gantry_length}"
      h="${gantry_length}" />

  </link>

  <!-- ********************** BASE *********************************  -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${-gantry_length/2-base_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}" />
      </geometry>
      <material name="Red">
        <color rgba="${255/255} ${0/255} ${0/255} 1.0" />
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 ${-gantry_length/2-base_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}" />
      </geometry>
    </collision>

    <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_length}"/>

  </link>

    <!-- Connect the GANTRY to the BASE -->
  <joint name="$base_joint" type="revolute"> <!-- WAIST -->
    <parent link="gantry_link" />
    <child link="$base_link" />
    <origin xyz="0 0 ${-gantry_length}" rpy="0 0 0" />
    <limit upper="${pi}" lower="-${pi}" effort="100" velocity="100" />
    <axis xyz="0 0 1" />
  </joint>


  <!-- *********************** BICEP ******************************  -->

  <link name="$bicep_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${bicep_width} ${bicep_height} ${bicep_length}" />
      </geometry>
      <material name="White">
        <color rgba="${255/255} ${255/255} ${255/255} 1.0" />
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${bicep_width} ${bicep_height} ${bicep_length}" />
      </geometry>
    </collision>

    <xacro:box_inertia m="${bicep_mass}" w="${bicep_width}" d="${bicep_height}"
      h="${bicep_length}" /> <!-- Chequear bien cual es w d h !!!!!!!!!!!!-->

  </link>

  <!-- Connect the BICEP to the BASE -->
  <joint name="$bicep_joint" type="revolute"> <!-- SHOULDER -->
    <parent link="base_link" />
    <child link="$bicep_link" />
    <origin xyz="0 0 ${-gantry_length-base_length}" rpy="0 0 0" />
    <limit upper="${pi/2}" lower="-${pi/2}" effort="100" velocity="100" />
    <axis xyz="0 1 0" />
  </joint>






</robot>