<?xml version="1.0"?>
<robot name="daniel_bot" xmlns:xacro="http://ros.org/wiki/xacro">

 <xacro:include filename="constants.xacro" />
 
  <!-- ****************** COORDINATES ORIGIN ***************************  -->
  <!-- Define the center of the robot -->
  <link name="world" />

  <!-- A simple fixed joint from our empty world link, to our base. -->
  <!-- The base origin is offset from the world origin. -->
  <joint name="gantry_joint" type="fixed">
    <origin xyz="0 0 2" rpy="0 0 0" />
    <parent link="world" />
    <child link="gantry_link" />
  </joint>

  <!-- ********************** GANTRY *********************************  -->
  <link name="gantry_link">
    <visual>
      <origin xyz="0 0 ${gantry_length/2} " rpy="0 0 0" />
      <geometry>
        <box size="${gantry_length} ${gantry_length} ${gantry_length}" />
      </geometry>
      <material name="red" />
    </visual>

    <collision>
      <origin xyz="0 0 ${gantry_length/2}" rpy="0 0 0" />
      <geometry>
        <box size="${gantry_length} ${gantry_length} ${gantry_length}" />
      </geometry>
    </collision>

    <xacro:box_inertia m="${gantry_mass}" w="${gantry_length}" d="${gantry_length}"
      h="${gantry_length}" z="${gantry_length/2}"/>

  </link>

  <!-- ********************** BASE *********************************  -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}" />
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}" />
      </geometry>
    </collision>

    <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_length}"/>

  </link>

    <!-- Connect the GANTRY to the BASE -->
  <joint name="base_joint" type="revolute"> <!-- WAIST -->
    <parent link="gantry_link" />
    <child link="base_link" />
    <origin xyz="0 0 ${-base_length/2}" rpy="0 0 0" />
    <limit upper="${pi}" lower="-${pi}" effort="100" velocity="100" />
    <axis xyz="0 0 1" />
  </joint>


  <!-- *********************** BICEP ******************************  -->

  <link name="bicep_link">
    <visual>
      <origin xyz="0 0 ${-bicep_length/2}" rpy="0 0 0" />
      <geometry>
        <box size="${bicep_width} ${bicep_height} ${bicep_length}" />
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${-bicep_length/2}" rpy="0 0 0" />
      <geometry>
        <box size="${bicep_width} ${bicep_height} ${bicep_length}" />
      </geometry>
    </collision>

    <xacro:box_inertia m="${bicep_mass}" w="${bicep_width}" d="${bicep_length}"
      h="${bicep_height}" z="${-bicep_length/2}"/> <!-- Chequear bien cual es w d h !!!!!!!!!!!!-->

  </link>

  <!-- Connect the BICEP to the BASE -->
  <joint name="bicep_joint" type="revolute"> <!-- SHOULDER -->
    <parent link="base_link" />
    <child link="bicep_link" />
    <origin xyz="0 0 ${-base_length/2}" rpy="0 0 0" />
    <limit upper="${pi/2}" lower="-${pi/2}" effort="100" velocity="100" />
    <axis xyz="0 1 0" />
  </joint>


</robot>